name: Auto Cherry-Pick from Upstream

on:
  # checkov:skip=CKV_GHA_7 The workflow requires user input for manual triggering
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to create the PR against'
        required: true
        default: 'main'
      script:
        description: 'Script to run after audit fix'
        required: false
        default: 'npm run all'

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: 'Akkjon'
      repo-name: 'close-milestone'
      base_branch: ${{ inputs.base_branch }}
      script: ${{ inputs.script || 'npm run all' }}
