name: Auto Cherry-Pick from Upstream

on:
  # checkov:skip=CKV_GHA_7 The workflow requires user input for manual triggering
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to create the PR against'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@upstream-Changes-CherryPick
    with:
      original-owner: 'Akkjon'
      repo-name: 'close-milestone'
      base_branch: ${{ inputs.base_branch }}
